name: Deploy to linode
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ self-hosted ]

    steps:
      - uses: actions/checkout@v2

      - deploy:
        run: |
          docker-compose build
          docker-compose up
