version: "2.2"
services:
  myblazorserverapp:
    build: ../../blazorwasm
    ports:
      - "8080:80"

  reverse_proxy:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=testsoftware.alexmickelson.guru
      - VALIDATION=http
      - STAGING=false
    volumes:
      - ./nginx.conf:/config/nginx/site-confs/default.conf
      - /data/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped