name: Deploy to linode
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ self-hosted ]

    steps:

      - name: deploy
        uses: actions/checkout@v2
        run: |
          docker-compose build
          docker-compose up
