name: Deploy to linode
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ self-hosted ]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: deploy
        run: |
          cd ops/production/
          docker-compose build
          docker-compose up -d
          docker restart swag
